"""Object art: cutouts in, square candidates out, published for the proposals page.

The subjects here are buildings and machines rather than characters -- the base,
the food bin, the shelter, an ore seam, a miner -- so they do not go through the
character normaliser in sprite_tool.py, which exists to hold a walk cycle's feet
on one anchor. What they need instead is the thing every object in this game
shares: a bottom edge that sits on the ground, and a size that says how much
detail survives the trip down to a tile.

Two things about the input are worth knowing before touching the numbers.

The cutouts arrive with a film of alpha=1 dust across the whole canvas -- three
of the four corners are 1, not 0 -- so a plain getbbox() on the alpha channel
returns the entire 1254 square and every subject looks like it fills its frame.
Everything here thresholds instead.

And RGBA resizing does not premultiply. Those dust pixels carry whatever colour
the matting left behind, and a straight LANCZOS pass smears it into the subject's
edge as a halo. So alpha is cleared below the threshold and the image is
premultiplied for the resize and unpremultiplied after.

    python3 motorio/tools/sprite/build_objects.py

Writes web/public/object-candidates/ and web/lib/generated/objects.json, which
is what /motorio/graphic/proposals reads.
"""
from __future__ import annotations

import hashlib
import io
import json
import re
import shutil
import sys
from pathlib import Path

from PIL import Image, ImageChops

REPO = Path(__file__).resolve().parents[3]
INBOX = Path.home() / "Workspace" / "Download"
# Beside refs/ and tiles/, which hold the other two kinds of source art. Inside
# tools/, so the originals stay in the repository without riding along in a Web
# export.
OBJECTS = REPO / "motorio" / "tools" / "sprite" / "objects"
# Published beside the sprite candidates, because that is where the page that
# shows them reads from. The first version of this wrote a graphic/proposals/
# directory at the repository root, which nothing serves -- the name refers to
# the page at /motorio/graphic/proposals, not to a folder.
PUBLISH_DIR = REPO / "web" / "public" / "object-candidates"
MANIFEST = REPO / "web" / "lib" / "generated" / "objects.json"

## The candidates that were chosen, and the size the game draws each at.
##
## Written down here rather than by copying a file into assets/ by hand, so the
## decision is recorded next to the thing that acts on it and a re-run cannot
## quietly disagree with what shipped.
##
## Exported at twice the drawn size, which is the convention the ground already
## follows: the snow atlas is stored at 64 and drawn at 32. The project filters
## textures with NEAREST, so an asset stored much larger than it is drawn throws
## most of its pixels away at a hard edge; twice leaves headroom for the zoom
## keys without turning the art to noise.
##
## The headroom is the point, and it is not spare: players play zoomed in, not at
## the default. `game_scale` reaches 1.6, and on a 1920 window that draws the
## core at 276 screen pixels against 173 stored. Measured 2026-08-13 -- a 1.6x
## NEAREST upscale, which survives only because this art is painted gradients
## rather than authored pixels. Anything crisper adopted here wants three times.
## Generated by gen_objects.py to match the characters. What shipped before was
## cool-toned semi-realistic steampunk beside a warm chibi cat, and it carried
## far more detail than survives 43 screen pixels. The `_gen` suffix keeps the
## lineage legible: everything without it came in from the cutout inbox.
ADOPTED = {
    # One tile each, as of 0.20.79. Nothing in the simulation changed -- the core
    # has always been one machine on one cell and the hut one cell beside it --
    # so at 2.7 and 2.2 tiles the buildings were pictures three times the size of
    # the thing they stood for, hanging over the tiles their neighbours are built
    # on. gen2 is drawn for the size: one silhouette and one light each, because
    # a door and a window and three pipes is twenty features in 32 pixels.
    # gen3 rather than gen2: gen2 was a stone ring with a fire in it, which reads
    # as a campfire -- something you sit at, not something you bring ore to. The
    # base throws heat *and* makes things, so the silhouette has to be built
    # rather than gathered.
    "core": ("core_gen3", 32),
    "shelter": ("shelter_gen2", 32),
    "food_bin": ("food_bin_gen1", 36),
    # Drawn at the miner's size rather than the 23 their painted bodies used.
    # These are one-tile machines standing on the snow, and one two thirds the
    # size of the miner beside it reads as a smaller class of thing rather than
    # as a different job.
    "generator": ("generator_gen1", 36),
    # gen2 rather than gen1: the first miner's drill leaned to one side, and the
    # direction a miner outputs in is already said by an arrow drawn over it.
    "miner": ("miner_gen2", 36),
    # The drill a working cat holds. Nothing rotates it and it bobs straight up
    # and down, so the bit has to point down in the art -- gen1 was a drill gun
    # aimed sideways, which reads as a cat holding a gun.
    "cat_tool": ("cat_tool_gen2", 21),  # a tool, not a machine
    # The case she wakes up beside, and the two things that come out of it. One
    # tile, because that is what it occupies -- the crate was a drawn grey
    # rectangle and what she carried was the same rectangle again, so the opening
    # had one shape for three different states.
    # Five pieces of the ship, drawn at one tile each. All five at the same size
    # on purpose: they are one kind of thing that happens to have five shapes,
    # and a field where some pieces are bigger reads as two kinds of wreck.
    "debris1": ("debris1_gen1", 30),
    "debris2": ("debris2_gen1", 30),
    "debris3": ("debris3_gen1", 30),
    "debris4": ("debris4_gen1", 30),
    "debris5": ("debris5_gen1", 30),
    # The second thing the game gives her, and until now the only one drawn in
    # code: a grey wedge on a brown stick, lying next to a painted case and a
    # painted hut. At 26 it is a little larger than the other drops because it is
    # the one the opening turns on.
    "pickaxe": ("pickaxe_gen1", 26),
    # The gun, at the pickaxe's size because the two are drawn by the same code
    # in the same two places -- the snow she finds them on and the slot they sit
    # in. Before this the slot showed a picture of a miner and so did the drop,
    # so the tool and the machine it puts down were one object twice.
    "build_gun": ("build_gun_gen1", 26),
    "kit": ("kit_gen1", 32),
    "kit_base": ("kit_base_gen1", 26),
    "kit_shelter": ("kit_shelter_gen1", 26),
    # 냥마을. The houses are the largest thing out there because they are what
    # the place is -- a cottage the size of the well beside it reads as a
    # garden ornament -- and the gate is drawn wider than its cell on purpose:
    # it is the one piece she walks *through*, so it has to span more than the
    # gap it stands in.
    "signpost": ("signpost_gen1", 30),
    "village_house": ("village_house_gen1", 38),
    "village_well": ("village_well_gen1", 30),
    "village_fire": ("village_fire_gen1", 32),
    "village_gate": ("village_gate_gen1", 40),
}
GAME_ART = REPO / "motorio" / "assets" / "objects"

## The three transport tiles are not chosen from candidates -- build_belt.py
## sweeps one measured cross-section along a line, an elbow and a T. They belong
## on the page anyway: the question the page answers is "what does each thing in
## the game look like now", and half an answer is the kind that goes stale.
BUILT = {"belt_straight": 32.0, "belt_corner": 32.0, "splitter": 32.0}

## What each piece is called, for people rather than for the code.
ADOPTED_NAMES = {
    "core": "기지 코어",
    "shelter": "숙소",
    "food_bin": "밥통",
    "miner": "채굴기",
    "cat_tool": "고양이 채굴 도구",
    "generator": "발전기",
    "belt_straight": "컨베이어 벨트 · 직선",
    "belt_corner": "컨베이어 벨트 · 코너",
    "splitter": "분배기",
    "debris1": "로켓잔해 · 노즈콘",
    "debris2": "로켓잔해 · 연료탱크",
    "debris3": "로켓잔해 · 엔진노즐",
    "debris4": "로켓잔해 · 선체판",
    "debris5": "로켓잔해 · 안테나",
    "pickaxe": "곡괭이",
    "build_gun": "건물건설총",
    "kit": "긴급 키트",
    "kit_base": "긴급기지키트",
    "kit_shelter": "긴급생존키트",
    "signpost": "표지판",
    "village_house": "냥마을 · 집",
    "village_well": "냥마을 · 우물",
    "village_fire": "냥마을 · 화롯불",
    "village_gate": "냥마을 · 입구",
}

## Anything at or below this is matting residue rather than art.
ALPHA_FLOOR = 16
SIZES = (128, 64)
## A little air under the subject so it does not sit flush against the frame.
BOTTOM_MARGIN = 3
## What counts as object art in the inbox: a bare subject name and a number, with
## or without the cutout tool's suffix. Deliberately narrow -- the same folder
## holds tile sheets like tile_rock_20.png, and a glob loose enough to sweep
## those up would move them somewhere they do not belong and only be noticed the
## next time a tileset failed to load.
INCOMING = re.compile(r"^([a-z]+)(\d+)(-Photoroom)?$")
## What counts once it is already in objects/. Wider than INCOMING because
## gen_objects.py writes `core_gen1`, and the narrowness above is about the
## inbox -- the folder that also holds tile sheets -- not about this one. Kept as
## a second pattern rather than by loosening the first, so broadening what the
## page displays cannot quietly change what gets moved out of Downloads.
CANDIDATE = re.compile(r"^([a-z][a-z_]*?)(\d+)$")


def clean(image: Image.Image) -> Image.Image:
    """Drop the matting dust, so the bounding box and the resize both see art."""
    out = image.convert("RGBA")
    alpha = out.getchannel("A").point(lambda v: 0 if v <= ALPHA_FLOOR else v)
    out.putalpha(alpha)
    return out


def content_box(image: Image.Image) -> tuple[int, int, int, int]:
    mask = image.getchannel("A").point(lambda v: 255 if v > ALPHA_FLOOR else 0)
    box = mask.getbbox()
    if box is None:
        raise SystemExit("빈 이미지입니다")
    return box


def fit(image: Image.Image, size: int) -> Image.Image:
    """Into a square, aspect kept, centred across and standing on the bottom.

    Bottom-aligned rather than centred because every one of these is an object
    that stands on a tile: a shelter floating half a cell above its own footprint
    reads as a bug in the game long before anyone suspects the art.
    """
    art = image.crop(content_box(image))
    room = size - BOTTOM_MARGIN
    scale = min(size / art.width, room / art.height)
    target = (max(1, round(art.width * scale)), max(1, round(art.height * scale)))
    small = _resize_rgba(art, target)

    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(small, ((size - target[0]) // 2, size - BOTTOM_MARGIN - target[1]))
    return canvas


def _resize_rgba(art: Image.Image, target: tuple[int, int]) -> Image.Image:
    """LANCZOS with the alpha carried properly.

    Pillow resizes the colour channels without regard to alpha, so the colour
    sitting under a transparent pixel is averaged into its neighbours and the
    subject grows a halo of whatever the matting left there. Multiplying the
    colour by alpha first makes transparent pixels contribute nothing, and
    dividing it back out afterwards restores the colour of what survived.
    """
    r, g, b, a = art.split()
    premultiplied = Image.merge("RGBA", (
        ImageChops.multiply(r, a), ImageChops.multiply(g, a), ImageChops.multiply(b, a), a))
    small = premultiplied.resize(target, Image.LANCZOS)
    sr, sg, sb, sa = small.split()
    return Image.merge("RGBA", (
        _unpremultiply(sr, sa), _unpremultiply(sg, sa), _unpremultiply(sb, sa), sa))


def _unpremultiply(channel: Image.Image, alpha: Image.Image) -> Image.Image:
    colour = list(channel.getdata())
    weight = list(alpha.getdata())
    restored = [0 if not w else min(255, round(c * 255 / w)) for c, w in zip(colour, weight)]
    out = Image.new("L", channel.size)
    out.putdata(restored)
    return out


def publish(image: Image.Image, name: str) -> str:
    """One content-hashed copy, returning the path the page asks for.

    Hashed for the same reason every other generated file here is: republishing
    under the old name keeps showing the old picture to anyone who already loaded
    it, and the candidate sheets learned that the hard way -- a corrected sheet
    sat behind a ten minute cache while the report said the fix had not landed.
    """
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    payload = buffer.getvalue()
    filename = f"{name}-{hashlib.sha256(payload).hexdigest()[:12]}.png"
    for old in PUBLISH_DIR.glob(f"{name}-*.png"):
        if old.name != filename:
            old.unlink()
    (PUBLISH_DIR / filename).write_bytes(payload)
    return "/object-candidates/" + filename


def shipped(role: str) -> Image.Image:
    """The file the game actually loads, ready to show.

    Not the candidate it came from: the candidate is cropped, bottom-aligned and
    resized on the way into assets/, so showing it would be showing something
    nobody sees. Resized only -- fitting it again would apply that pass twice.
    """
    return clean(Image.open(GAME_ART / f"{role}.png"))


## East, south, west, north -- the order the game rotates by, and the order a
## clockwise turn steps through.
HEADINGS = [(1, 0), (0, 1), (-1, 0), (0, -1)]


def belt_loop() -> Image.Image:
    """The transport tiles assembled, so the joins can be looked at.

    A picture of a straight tile proves nothing about the thing that matters,
    which is whether two of them meet without a line down the join.

    The orientations are derived from the path rather than written down. The
    first version of this listed a rotation per cell and two of the four corners
    were wrong -- which is the same failure the game avoids by reading its
    neighbours instead of storing a picture, arriving here because the preview
    was allowed its own copy of the rule. So this walks the path, works out how
    each cell is entered and left, and applies exactly what MachineLayer applies:
    rotate by the way it was entered, mirror when the turn is anticlockwise.
    """
    straight = shipped("belt_straight")
    corner = shipped("belt_corner")
    split = shipped("splitter")
    size = straight.width

    # A closed loop, which contains all four clockwise corners, and an S-bend
    # under it, which is where the anticlockwise ones are. Both are needed: a
    # mirror that is applied the wrong way round looks perfect on one of them.
    loop = [(1, 0), (2, 0), (3, 0), (3, 1), (3, 2), (2, 2), (1, 2), (0, 2),
            (0, 1), (0, 0)]
    bend = [(0, 4), (1, 4), (1, 3), (2, 3), (2, 4), (3, 4)]
    splitter_at = (1, 2)

    canvas = Image.new("RGBA", (size * 4, size * 5), (222, 228, 236, 255))
    for path, closed in [(loop, True), (bend, False)]:
        for index, cell in enumerate(path):
            if closed:
                previous = path[index - 1]
                following = path[(index + 1) % len(path)]
            else:
                previous = path[max(0, index - 1)]
                following = path[min(len(path) - 1, index + 1)]
            inflow = (cell[0] - previous[0], cell[1] - previous[1])
            outflow = (following[0] - cell[0], following[1] - cell[1])
            # The ends of an open path have nothing on one side; a belt with
            # nothing feeding it draws straight, exactly as in the game.
            if inflow == (0, 0):
                inflow = outflow
            if outflow == (0, 0):
                outflow = inflow

            if cell == splitter_at:
                # Turned by the way it faces, same as the game does it. Its two
                # output arms are the sides, which is why nothing here mirrors.
                art = _quarters(split, HEADINGS.index(outflow))
            elif inflow == outflow:
                art = _quarters(straight, HEADINGS.index(outflow))
            else:
                clockwise = (-inflow[1], inflow[0]) == outflow
                art = corner if clockwise else corner.transpose(Image.FLIP_TOP_BOTTOM)
                art = _quarters(art, HEADINGS.index(inflow))
            canvas.alpha_composite(art, (cell[0] * size, cell[1] * size))
    return canvas


def _quarters(art: Image.Image, turns: int) -> Image.Image:
    """Clockwise quarter turns. PIL rotates anticlockwise, hence ROTATE_270."""
    for _turn in range(turns % 4):
        art = art.transpose(Image.ROTATE_270)
    return art


def main() -> int:
    OBJECTS.mkdir(parents=True, exist_ok=True)
    PUBLISH_DIR.mkdir(parents=True, exist_ok=True)
    if not MANIFEST.parent.is_dir():
        print(f"{MANIFEST.parent}가 없습니다. 사이트가 매니페스트를 읽는 곳이므로 "
              f"디렉터리를 만들 것이 아니라 경로가 낡은 것입니다.", file=sys.stderr)
        return 1

    incoming = sorted(path for path in INBOX.glob("*.png") if INCOMING.match(path.stem))
    for source in incoming:
        subject_name, number, _ = INCOMING.match(source.stem).groups()
        target = OBJECTS / f"{subject_name}{number}.png"
        shutil.move(str(source), target)
        print("옮김: %s -> %s" % (source.name, target.relative_to(REPO)))
    if not incoming:
        print("새 파일 없음 -- 기존 원본으로 다시 그립니다")

    # Everything in objects/, not only what arrived today. A subject that gained
    # three new candidates needs its entry rewritten with all six, and a run that
    # only knew about the new ones would publish a list missing half its options.
    subjects: dict[str, list[dict]] = {}
    for path in sorted(OBJECTS.glob("*.png")):
        match = CANDIDATE.match(path.stem)
        if match is None:
            print("건너뜀 (이름 규칙 밖): %s" % path.name)
            continue
        art = clean(Image.open(path))
        box = content_box(art)
        subjects.setdefault(match.group(1), []).append({
            "id": path.stem,
            "number": int(match.group(2)),
            "sizes": {str(size): publish(fit(art, size), f"{path.stem}-{size}")
                      for size in SIZES},
            "source": [box[2] - box[0], box[3] - box[1]],
        })

    manifest = {"subjects": []}
    for subject, members in sorted(subjects.items()):
        members.sort(key=lambda item: item["number"])
        manifest["subjects"].append({"id": subject, "candidates": members})
        print("%-8s %d개: %s" % (subject, len(members),
                                 ", ".join(m["id"] for m in members)))
    # And the ones that were chosen, into the game.
    GAME_ART.mkdir(parents=True, exist_ok=True)
    for role, (candidate, draw) in sorted(ADOPTED.items()):
        source = OBJECTS / f"{candidate}.png"
        if not source.exists():
            print("채택본 없음: %s -> %s" % (role, source.name), file=sys.stderr)
            return 1
        stored = int(round(draw * 2))
        fit(clean(Image.open(source)), stored).save(GAME_ART / f"{role}.png")
        print("게임: %-9s <- %-9s %dpx (그릴 크기 %.1f = %.2f칸)"
              % (role, candidate, stored, draw, draw / 32.0))

    # And what shipped, for the page. Written after the export above so it can
    # only ever describe files that exist, and taken from assets/ rather than
    # from the candidate, so the page shows the picture the game loads.
    chosen: list[dict] = []
    for role in sorted(list(ADOPTED) + list(BUILT)):
        if not (GAME_ART / f"{role}.png").exists():
            print("배포본 없음: %s" % role, file=sys.stderr)
            return 1
        art = shipped(role)
        draw = BUILT[role] if role in BUILT else ADOPTED[role][1]
        chosen.append({
            "role": role,
            "name": ADOPTED_NAMES.get(role, role),
            "from": "build_belt.py" if role in BUILT else ADOPTED[role][0],
            "draw": draw,
            "stored": art.width,
            # At the size the game draws it as well as large. The small one is
            # the one that decides whether a piece works; the large one is only
            # so the choice can be looked at.
            "sizes": {str(size): publish(art.resize((size, size), Image.LANCZOS),
                                         f"shipped-{role}-{size}")
                      for size in (128, int(round(draw)))},
        })
    manifest["adopted"] = chosen
    manifest["belt_loop"] = publish(belt_loop(), "shipped-belt-loop")
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=1) + "\n",
                        encoding="utf-8")
    print("채택본 %d개 + 벨트 고리를 페이지로 발행" % len(chosen))

    # Files nothing in the manifest points at any more, so a retired subject does
    # not leave its renders published and unreachable. Last, and reading the
    # finished manifest: when this ran before the shipped art was published it
    # deleted the previous run's copies of it every time, which worked only
    # because the next few lines happened to put them back.
    referenced = {url.rsplit("/", 1)[-1]
                  for entry in manifest["subjects"]
                  for candidate in entry["candidates"]
                  for url in candidate["sizes"].values()}
    referenced |= {url.rsplit("/", 1)[-1]
                   for entry in manifest["adopted"]
                   for url in entry["sizes"].values()}
    referenced.add(manifest["belt_loop"].rsplit("/", 1)[-1])
    for stale in PUBLISH_DIR.glob("*.png"):
        if stale.name not in referenced:
            stale.unlink()
            print("정리: %s" % stale.name)
    print("매니페스트: %s" % MANIFEST.relative_to(REPO))
    return 0


if __name__ == "__main__":
    sys.exit(main())
