extends RefCounted
class_name RockTiles

## Generated by tools/sprite/build_rock_corners.py from build_terrain.py.
## Do not edit by hand.
##
## Which cell of assets/tiles/rock_47.png a rock cell draws, indexed by
## its eight neighbours: bit 1 north, 2 east, 4 south, 8 west, 16 north-
## east, 32 south-east, 64 south-west, 128 north-west.
##
## 256 entries rather than 47 because the caller should not have to know
## that a diagonal only matters when both of its orthogonals are rock.
## The table folds that rule in, so a raw neighbour mask indexes it
## directly and two masks that must look the same cannot drift apart.
##
## Every configuration here is exact. The tiles are assembled from corner
## pieces rather than drawn one by one, so a seam can only be wrong if the
## five pieces disagree with each other -- not if 47 drawings do.
const ATLAS: Texture2D = preload("res://assets/tiles/rock_47.png")
const ATLAS_COLUMNS := 8
const CELL := 64.0

const LOOKUP: Array[int] = [
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
	0, 1, 2, 16, 4, 5, 6, 17, 8, 9, 10, 18, 12, 13, 14, 19,
	0, 1, 2, 3, 4, 5, 20, 21, 8, 9, 10, 11, 12, 13, 22, 23,
	0, 1, 2, 16, 4, 5, 20, 24, 8, 9, 10, 18, 12, 13, 22, 25,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 26, 27, 28, 29,
	0, 1, 2, 16, 4, 5, 6, 17, 8, 9, 10, 18, 26, 27, 28, 30,
	0, 1, 2, 3, 4, 5, 20, 21, 8, 9, 10, 11, 26, 27, 31, 32,
	0, 1, 2, 16, 4, 5, 20, 24, 8, 9, 10, 18, 26, 27, 31, 33,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 34, 10, 35, 12, 36, 14, 37,
	0, 1, 2, 16, 4, 5, 6, 17, 8, 34, 10, 38, 12, 36, 14, 39,
	0, 1, 2, 3, 4, 5, 20, 21, 8, 34, 10, 35, 12, 36, 22, 40,
	0, 1, 2, 16, 4, 5, 20, 24, 8, 34, 10, 38, 12, 36, 22, 41,
	0, 1, 2, 3, 4, 5, 6, 7, 8, 34, 10, 35, 26, 42, 28, 43,
	0, 1, 2, 16, 4, 5, 6, 17, 8, 34, 10, 38, 26, 42, 28, 44,
	0, 1, 2, 3, 4, 5, 20, 21, 8, 34, 10, 35, 26, 42, 31, 45,
	0, 1, 2, 16, 4, 5, 20, 24, 8, 34, 10, 38, 26, 42, 31, 46,
]

## Where in the atlas one of those cells lives.
static func region(slot: int) -> Rect2:
	var index: int = clampi(slot, 0, 46)
	return Rect2(float(index % ATLAS_COLUMNS) * CELL,
		float(index / ATLAS_COLUMNS) * CELL, CELL, CELL)
